name: Deploy to AWS
on:
  push:
    branches:
      - "main"
env:
  AWS_REGION: ap-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  PEM_SSH_KEY: ${{ secrets.AWS_PEM_KEY }}
  SERVER_PUBLIC_IP: ${{ secrets.AWS_EC2_IP }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_PUBLIC_KEY }}
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.AWS_PEM_KEY }}" > ~/.ssh/taxikey.pem
          chmod 400 ~/.ssh/taxikey.pem
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.AWS_EC2_IP }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 654654264414.dkr.ecr.ap-south-1.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Build, push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ecr-web-image
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          docker buildx build --platform linux/amd64 -t $REGISTRY/$REPOSITORY .
          docker push $REGISTRY/$REPOSITORY
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 654654264414.dkr.ecr.ap-south-1.amazonaws.com
      - name: Stop and remove existing container
        run: |
         sudo docker stop ecr-web-image || true
          sudo docker rm ecr-web-image || true
      - name: Pull latest Docker image
        run: |
          docker pull 654654264414.dkr.ecr.ap-south-1.amazonaws.com/ecr-web-image
      - name: Run Docker container
        run: |
         sudo docker run --rm -d --name ecr-web-image -p 80:80 654654264414.dkr.ecr.ap-south-1.amazonaws.com/ecr-web-image
      - name: Cleanup SSH key
        run: |
          rm ~/.ssh/id_rsa
