name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull $DOCKER_USERNAME"/newdocker233/ecr-web-image"

      - name: Delete old container
        run: sudo docker rm -f ecr-web-image-container || true

      - name: Run Container
        run: sudo docker run -d -p 8080:8080 --name ecr-web-image-container $DOCKER_USERNAME"/newdocker233/ecr-web-image"
